# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/p839v55/setup-makefiles.sh

# Prebuilt APK
PRODUCT_PACKAGES += \
    TimeService

# Prebuilt Framework
PRODUCT_PACKAGES += \
    qncvitems \
    qcrilhook

# Prebuilt vendor/lib needed for compilation
PRODUCT_PACKAGES += \
    libtime_genoff \
    libloc_ds_api \
    libloc_api_v02

$(call inherit-product, vendor/vodafone/p839v55/p839v55-vendor-blobs.mk)
